### ISSUE TITLE
さん

### ISSUE THREAD

**Issue by honjo2** [honjo2/react-issue-ganttchart#3]
```yaml
start_date: 2021/7/18
due_date: 2021/7/20
progress: 0.1
parent: 4
```
