### ISSUE TITLE
よん下

### ISSUE THREAD

**Issue by honjo2** [honjo2/react-issue-ganttchart#5]
```yaml
start_date: 2021/7/18
due_date: 2021/7/19
progress: 0.1
parent: 4
```
